//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotNetDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceInfo
    {
        public int DeivceId { get; set; }
        public string DeviceName { get; set; }
        public string Department { get; set; }
        public string UserName { get; set; }
        public string Phone { get; set; }
        public string DeviceConfig { get; set; }
        public string MacAddress { get; set; }
        public string DeviceBrand { get; set; }
        public string DeviceMode { get; set; }
        public string PurchaseDate { get; set; }
        public string DeviceStatus { get; set; }
        public string Comment { get; set; }
    }
}
