//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotNetDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintanceInfo
    {
        public int MaintanceId { get; set; }
        public string DeviceId { get; set; }
        public string Maintainer { get; set; }
        public string DeviceName { get; set; }
        public string MaintanceReason { get; set; }
        public string MaintanceResult { get; set; }
        public string Comment { get; set; }
    }
}
