//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotNetDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemInfo
    {
        public string SystemName { get; set; }
        public string SystemIP { get; set; }
        public string SystemRunTime { get; set; }
        public string SystemInfo1 { get; set; }
        public int Id { get; set; }
    }
}
